enum AutomatedEmailType {
  BOOKING_INSTRUCTIONS = 'BOOKING_INSTRUCTIONS',
  BOOKING_INSTRUCTIONS_REMINDER = 'BOOKING_INSTRUCTIONS_REMINDER',
  BOOKING_CONFIRMATION = 'BOOKING_CONFIRMATION',
  BOOKING_REJECTION = 'BOOKING_REJECTION',
  BOOKING_CANCELLATION = 'BOOKING_CANCELLATION',
  BOOKING_REMINDER = 'BOOKING_REMINDER',
  BOOKING_FEEDBACK_REQUEST = 'BOOKING_FEEDBACK_REQUEST',
}

export default AutomatedEmailType;