enum BookingStatus {
  PENDING = 'PENDING',
  REJECTED = 'REJECTED',
  BOOKED = 'BOOKED',
  OUT_FOR_DELIVERY = 'OUT_FOR_DELIVERY',
  DELIVERED = 'DELIVERED',
  CANCELLED = 'CANCELLED',
  COMPLETED = 'COMPLETED',
}

export default BookingStatus;
