enum BookingFlexibilityLevel {
  NO_OTHER_CARS = 'NO_OTHER_CARS',
  SAME_MODEL_SAME_PRICE = 'SAME_MODEL_SAME_PRICE',
  SAME_MODEL_ANY_PRICE = 'SAME_MODEL_ANY_PRICE',
  SAME_TYPE_SAME_PRICE = 'SAME_TYPE_SAME_PRICE',
  SAME_TYPE_ANY_PRICE = 'SAME_TYPE_ANY_PRICE',
}

export default BookingFlexibilityLevel;
