enum BookingCompletionKey {
  ID_CARD_OR_PASSPORT_SUBMITTED = 'ID_CARD_OR_PASSPORT_SUBMITTED',
  DRIVER_LICENSE_SUBMITTED = 'DRIVER_LICENSE_SUBMITTED',  
  OTHER_DOCUMENTS_SUBMITTED = 'OTHER_DOCUMENTS_SUBMITTED',
  PAYMENT_EVIDENCE_SUBMITTED = 'PAYMENT_EVIDENCE_SUBMITTED',
}

export default BookingCompletionKey;