enum BookingStatus {
  PENDING = "PENDING",
  REJECTED = "REJECTED",
  ACCEPTED = "ACCEPTED",
  CONFIRMED = "CONFIRMED",
  OUT_FOR_DELIVERY = "OUT_FOR_DELIVERY",
  CANCELLED = "CANCELLED",
  DISPUTED = "DISPUTED",
  DELIVERED = "DELIVERED",
  COMPLETED = "COMPLETED"
}

export default BookingStatus;
