const enum BookingAdditionalFee {
  OUT_OF_OPERATING_HOURS_DELIVERY = 'OUT_OF_OPERATING_HOURS_DELIVERY',
  OUT_OF_OPERATING_HOURS_RETURN = 'OUT_OF_OPERATING_HOURS_PICKUP',
  OUT_OF_FREE_SERVICE_AREA_DELIVERY = 'OUT_OF_FREE_SERVICE_AREA_DELIVERY',
  OUT_OF_FREE_SERVICE_AREA_RETURN = 'OUT_OF_FREE_SERVICE_AREA_RETURN',
}

export default BookingAdditionalFee;