enum BookingAction {
  EDIT = 'EDIT',
  UPLOAD_DOCUMENTS = 'UPLOAD_DOCUMENTS',
  VIEW_DOCUMENTS = 'VIEW_DOCUMENTS',
  PAY_DEPOSIT = 'PAY_DEPOSIT',
  SEND_EMAIL = 'SEND_EMAIL',
  ACCEPT = 'ACCEPT',
  REJECT = 'REJECT',
  CANCEL = 'CANCEL',
}

export default BookingAction;