enum IncidentType {
  UNPAID_BOOKING_DEPOSIT = 'UNPAID_BOOKING_DEPOSIT',
  CANCELED_PAID_BOOKING_BY_CUSTOMER = 'CANCELED_PAID_BOOKING_BY_CUSTOMER',
  CANCELED_PAID_BOOKING_BY_SHOP = 'CANCELED_PAID_BOOKING_BY_SHOP',
  UNCONFIRMED_BOOKING = 'UNCONFIRMED_BOOKING',
  CANCELED_CONFIRMED_BOOKING_BY_CUSTOMER = 'CANCELED_CONFIRMED_BOOKING_BY_CUSTOMER',
  CANCELED_CONFIRMED_BOOKING_BY_SHOP = 'CANCELED_CONFIRMED_BOOKING_BY_SHOP'
}

export default IncidentType;