import CarModel from '../types/CarModel';
import CarFuel from '../types/CarFuel';

const CarFuelsByModel: {[key in CarModel]: CarFuel[]} = {
  ['Yaris Ativ']: ["Petrol"],
  ['Yaris']: ["Petrol"],
  ['Vios']: ["Petrol"],
  ['Fortuner']: ["Diesel"],
  ['Corolla Altis']: ["Petrol"],
  ['Corolla Cross']: ["Petrol","Hybrid"],
  ['CAMRY']: ["Hybrid"],
  ['Yaris Cross']: ["Hybrid"],
  ['Veloz']: ["Petrol"],
  ['Innova Zenix']: ["Hybrid"],
  ['Alphard']: ["Petrol","Hybrid"],
  ['Hilux Champ']: ["Diesel"],
  ['Hilux Vego']: ["Diesel"],
  ['Hilux Revo']: ["Diesel"],
  ['Hiace']: ["Diesel"],
  ['Commuter']: ["Diesel"],
  ['Majesty']: ["Diesel"],
  ['Mu-x']: ["Diesel"],
  ['City']: ["Petrol","Hybrid"],
  ['City Hatchback']: ["Petrol","Hybrid"],
  ['BR-V']: ["Petrol"],
  ['WR-V']: ["Petrol"],
  ['Civic']: ["Petrol"],
  ['Accord e:HEV']: ["Hybrid"],
  ['HR-V e:HEV']: ["Hybrid"],
  ['CR-V']: ["Petrol","Hybrid"],
  ['e:N1']: ["Electric"],
  ['Everest']: ["Diesel"],
  ['Ranger']: ["Diesel"],
  ['Mirage']: ["Petrol"],
  ['Attrage']: ["Petrol"],
  ['Xpander']: ["Petrol","Hybrid"],
  ['Xforce']: ["Hybrid"],
  ['Triton']: ["Diesel"],
  ['Pajero']: ["Diesel"],
  ['Atto 3']: ["Electric"],
  ['Dolphin']: ["Electric"],
  ['Seal']: ["Electric"],
  ['Sealion 7']: ["Electric"],
  ['M6']: ["Electric"],
  ['Seal 5']: ["Hybrid"],
  ['3']: ["Hybrid"],
  ['5']: ["Petrol"],
  ['4']: ["Electric"],
  ['ZS']: ["Petrol","Electric"],
  ['HS']: ["Hybrid"],
  ['EP']: ["Electric"],
  ['ES']: ["Electric"],
  ['VS']: ["Hybrid"],
  ['Maxus 7']: ["Electric"],
  ['Maxus 9']: ["Electric"],
  ['IM6']: ["Electric"],
  ['S5']: ["Electric"],
  ['Cyberster']: ["Electric"],
  ['Extender']: ["Diesel"],
  ['2 Sedan']: ["Petrol"],
  ['2 Hatchback']: ["Petrol"],
  ['3 Sedan']: ["Petrol"],
  ['3 Fastback']: ["Petrol"],
  ['MX-5']: ["Petrol"],
  ['CX-3']: ["Petrol","Diesel"],
  ['CX-30']: ["Petrol","Hybrid"],
  ['CX-5']: ["Petrol","Diesel"],
  ['CX-8']: ["Petrol","Diesel"],
  ['BT-50']: ["Diesel"],
  ['Almera']: ["Petrol"],
  ['Sylphy']: ["Petrol"],
  ['Note']: ["Hybrid"],
  ['Kicks']: ["Hybrid"],
  ['X-Trail']: ["Petrol","Hybrid"],
  ['Terra']: ["Diesel"],
  ['Navara']: ["Diesel"],
  ['Serena']: ["Hybrid"],
  ['GT-R']: ["Petrol"],
  ['Leaf']: ["Electric"],
  ['Neta V']: ["Electric"],
  ['Neta V-II']: ["Electric"],
  ['Neta X']: ["Electric"],
  ['Haval H6']: ["Hybrid"],
  ['Good Cat']: ["Electric"],
  ['07']: ["Electric"],
  ['300']: ["Diesel","Hybrid"],
  ['500']: ["Hybrid"],
  ['Y Plus']: ["Electric"],
  ['V']: ["Electric"],
  ['UT']: ["Electric"],
  ['M8']: ["Hybrid"],
  ['L07']: ["Electric"],
  ['S07']: ["Electric"],
  ['S05']: ["Electric"],
  ['G6']: ["Electric"],
  ['X9']: ["Electric"],
  ['X']: ["Electric"],
  ['009']: ["Electric"],
  ['6']: ["Electric"],
  ['Santa Fe']: ["Hybrid"],
  ['Stargazer']: ["Petrol"],
  ['Staria']: ["Diesel"],
  ['H-1']: ["Diesel"],
  ['EV5']: ["Electric"],
  ['EV9']: ["Electric"],
  ['Carnival']: ["Diesel"],
  ['3 Series']: ["Petrol","Diesel","Hybrid"],
  ['5 Series']: ["Petrol","Diesel","Hybrid"],
  ['7 Series Sedan']: ["Diesel","Hybrid"],
  ['i5']: ["Electric"],
  ['i7']: ["Electric"],
  ['X1']: ["Petrol"],
  ['X3']: ["Diesel"],
  ['Z4 Roadster']: ["Petrol"],
  ['C-Class Saloon']: ["Petrol"],
  ['E-Class Saloon']: ["Petrol"],
  ['GLC SUV']: ["Petrol"],
  ['GLA SUV']: ["Petrol"],
  ['S-Class Saloon']: ["Petrol"],
};

export default Object.freeze(CarFuelsByModel);
