import CarModel from '../types/CarModel';

const CarSeatsByModel: {[key in CarModel]: number[]} = {
  ['Yaris Ativ']: [5],
  ['Yaris']: [5],
  ['Vios']: [5],
  ['Fortuner']: [7],
  ['Corolla Altis']: [5],
  ['Corolla Cross']: [5],
  ['CAMRY']: [5],
  ['Yaris Cross']: [5],
  ['Veloz']: [7],
  ['Innova Zenix']: [7],
  ['Alphard']: [7],
  ['Hilux Champ']: [2],
  ['Hilux Vego']: [2,5],
  ['Hilux Revo']: [2,5],
  ['Hiace']: [12],
  ['Commuter']: [15],
  ['Majesty']: [11],
  ['Mu-x']: [7],
  ['City']: [5],
  ['City Hatchback']: [5],
  ['BR-V']: [7],
  ['WR-V']: [5],
  ['Civic']: [5],
  ['Accord e:HEV']: [5],
  ['HR-V e:HEV']: [5],
  ['CR-V']: [5],
  ['e:N1']: [5],
  ['Everest']: [7],
  ['Ranger']: [5],
  ['Mirage']: [5],
  ['Attrage']: [5],
  ['Xpander']: [7],
  ['Xforce']: [5],
  ['Triton']: [5],
  ['Pajero']: [7],
  ['Atto 3']: [5],
  ['Dolphin']: [5],
  ['Seal']: [5],
  ['Sealion 7']: [5],
  ['M6']: [6],
  ['Seal 5']: [5],
  ['MG 3']: [5],
  ['MG 5']: [5],
  ['MG 4']: [5],
  ['MG ZS']: [5],
  ['MG HS']: [5],
  ['MG EP']: [5],
  ['MG ES']: [5],
  ['MG VS']: [5],
  ['MG Maxus 7']: [7],
  ['MG Maxus 9']: [7],
  ['MG IM6']: [5],
  ['MG S5']: [5],
  ['MG Cyberster']: [2],
  ['MG Extender']: [5],
  ['Mazda 2 Sedan']: [5],
  ['Mazda 2 Hatchback']: [5],
  ['Mazda 3 Sedan']: [5],
  ['Mazda 3 Fastback']: [5],
  ['Mazda MX-5']: [2],
  ['Mazda CX-3']: [5],
  ['Mazda CX-30']: [5],
  ['Mazda CX-5']: [5],
  ['Mazda CX-8']: [6,7],
  ['Mazda BT-50']: [5],
  ['Almera']: [5],
  ['Sylphy']: [5],
  ['Note']: [5],
  ['Kicks']: [5],
  ['X-Trail']: [5,7],
  ['Terra']: [7],
  ['Navara']: [5],
  ['Serena']: [7],
  ['GT-R']: [2],
  ['Leaf']: [5],
  ['Neta V']: [5],
  ['Neta V-II']: [5],
  ['Neta X']: [5],
  ['Haval H6']: [5],
  ['Good Cat']: [5],
  ['07']: [5],
  ['Tank 300']: [5],
  ['Tank 500']: [7],
  ['Aion Y Plus']: [5],
  ['Aion V']: [5],
  ['Aion UT']: [5],
  ['M8']: [7],
  ['L07']: [5],
  ['S07']: [5],
  ['S05']: [5],
  ['G6']: [5],
  ['X9']: [7],
  ['X']: [5],
  ['009']: [7],
  ['6']: [5],
  ['Santa Fe']: [5],
  ['Stargazer']: [6,7],
  ['Staria']: [7,11],
  ['H-1']: [11],
  ['EV5']: [5],
  ['EV9']: [6],
  ['Carnival']: [11],
  ['3 Series']: [5],
  ['5 Series']: [5],
  ['7 Series Sedan']: [5],
  ['i5']: [5],
  ['i7']: [5],
  ['X1']: [5],
  ['X3']: [5],
  ['Z4 Roadster']: [2],
  ['C-Class Saloon']: [5],
  ['E-Class Saloon']: [5],
  ['GLC SUV']: [5],
  ['GLA SUV']: [5],
  ['S-Class Saloon']: [5],
};

export default Object.freeze(CarSeatsByModel);
