import CarModel from '../types/CarModel';
import CarType from '../types/CarType';

const CarTypesByModel: {[key in CarModel]: CarType} = {
  ['Yaris Ativ']: "Sedan",
  ['Yaris']: "Hatchback",
  ['Vios']: "Sedan",
  ['Fortuner']: "SUV & PPV",
  ['Corolla Altis']: "Sedan",
  ['Corolla Cross']: "SUV & PPV",
  ['CAMRY']: "Sedan",
  ['Yaris Cross']: "SUV & PPV",
  ['Veloz']: "SUV & PPV",
  ['Innova Zenix']: "SUV & PPV",
  ['Alphard']: "MPV & Van",
  ['Hilux Champ']: "Pickup",
  ['Hilux Vego']: "Pickup",
  ['Hilux Revo']: "Pickup",
  ['Hiace']: "MPV & Van",
  ['Commuter']: "MPV & Van",
  ['Majesty']: "MPV & Van",
  ['Mu-x']: "SUV & PPV",
  ['City']: "Sedan",
  ['City Hatchback']: "Hatchback",
  ['BR-V']: "MPV & Van",
  ['WR-V']: "SUV & PPV",
  ['Civic']: "Sedan",
  ['Accord e:HEV']: "Sedan",
  ['HR-V e:HEV']: "SUV & PPV",
  ['CR-V']: "SUV & PPV",
  ['e:N1']: "SUV & PPV",
  ['Everest']: "SUV & PPV",
  ['Ranger']: "Pickup",
  ['Mirage']: "Hatchback",
  ['Attrage']: "Sedan",
  ['Xpander']: "SUV & PPV",
  ['Xforce']: "SUV & PPV",
  ['Triton']: "Pickup",
  ['Pajero']: "SUV & PPV",
  ['Atto 3']: "SUV & PPV",
  ['Dolphin']: "Hatchback",
  ['Seal']: "Sedan",
  ['Sealion 7']: "SUV & PPV",
  ['M6']: "MPV & Van",
  ['Seal 5']: "Sedan",
  ['MG 3']: "Hatchback",
  ['MG 5']: "Sedan",
  ['MG 4']: "Hatchback",
  ['MG ZS']: "SUV & PPV",
  ['MG HS']: "SUV & PPV",
  ['MG EP']: "SUV & PPV",
  ['MG ES']: "SUV & PPV",
  ['MG VS']: "SUV & PPV",
  ['MG Maxus 7']: "MPV & Van",
  ['MG Maxus 9']: "MPV & Van",
  ['MG IM6']: "SUV & PPV",
  ['MG S5']: "SUV & PPV",
  ['MG Cyberster']: "Coupe",
  ['MG Extender']: "Pickup",
  ['Mazda 2 Sedan']: "Sedan",
  ['Mazda 2 Hatchback']: "Hatchback",
  ['Mazda 3 Sedan']: "Sedan",
  ['Mazda 3 Fastback']: "Hatchback",
  ['Mazda MX-5']: "Convertible",
  ['Mazda CX-3']: "SUV & PPV",
  ['Mazda CX-30']: "SUV & PPV",
  ['Mazda CX-5']: "SUV & PPV",
  ['Mazda CX-8']: "SUV & PPV",
  ['Mazda BT-50']: "Pickup",
  ['Almera']: "Sedan",
  ['Sylphy']: "Sedan",
  ['Note']: "Hatchback",
  ['Kicks']: "SUV & PPV",
  ['X-Trail']: "SUV & PPV",
  ['Terra']: "SUV & PPV",
  ['Navara']: "Pickup",
  ['Serena']: "MPV & Van",
  ['GT-R']: "Coupe",
  ['Leaf']: "Hatchback",
  ['Neta V']: "Hatchback",
  ['Neta V-II']: "Hatchback",
  ['Neta X']: "SUV & PPV",
  ['Haval H6']: "SUV & PPV",
  ['Good Cat']: "Hatchback",
  ['07']: "Sedan",
  ['Tank 300']: "SUV & PPV",
  ['Tank 500']: "SUV & PPV",
  ['Aion Y Plus']: "SUV & PPV",
  ['Aion V']: "SUV & PPV",
  ['Aion UT']: "Hatchback",
  ['M8']: "MPV & Van",
  ['L07']: "Sedan",
  ['S07']: "SUV & PPV",
  ['S05']: "SUV & PPV",
  ['G6']: "SUV & PPV",
  ['X9']: "MPV & Van",
  ['X']: "SUV & PPV",
  ['009']: "MPV & Van",
  ['6']: "SUV & PPV",
  ['Santa Fe']: "SUV & PPV",
  ['Stargazer']: "MPV & Van",
  ['Staria']: "MPV & Van",
  ['H-1']: "MPV & Van",
  ['EV5']: "SUV & PPV",
  ['EV9']: "SUV & PPV",
  ['Carnival']: "MPV & Van",
  ['3 Series']: "Sedan",
  ['5 Series']: "Sedan",
  ['7 Series Sedan']: "Sedan",
  ['i5']: "Sedan",
  ['i7']: "Sedan",
  ['X1']: "SUV & PPV",
  ['X3']: "SUV & PPV",
  ['Z4 Roadster']: "Convertible",
  ['C-Class Saloon']: "Sedan",
  ['E-Class Saloon']: "Sedan",
  ['GLC SUV']: "SUV & PPV",
  ['GLA SUV']: "SUV & PPV",
  ['S-Class Saloon']: "Sedan",
};

export default Object.freeze(CarTypesByModel);
