import CarModel from '../types/CarModel';
import CarTransmission from '../types/CarTransmission';

const CarTransmissionsByModel: {[key in CarModel]: CarTransmission[]} = {
  ['Yaris Ativ']: ["Automatic"],
  ['Yaris']: ["Automatic"],
  ['Vios']: ["Automatic","Manual"],
  ['Fortuner']: ["Automatic","Manual"],
  ['Corolla Altis']: ["Automatic","Manual"],
  ['Corolla Cross']: ["Automatic","Manual"],
  ['CAMRY']: ["Automatic","Manual"],
  ['Yaris Cross']: ["Automatic","Manual"],
  ['Veloz']: ["Automatic","Manual"],
  ['Innova Zenix']: ["Automatic","Manual"],
  ['Alphard']: ["Automatic","Manual"],
  ['Hilux Champ']: ["Automatic","Manual"],
  ['Hilux Vego']: ["Automatic","Manual"],
  ['Hilux Revo']: ["Automatic","Manual"],
  ['Hiace']: ["Automatic","Manual"],
  ['Commuter']: ["Automatic","Manual"],
  ['Majesty']: ["Automatic","Manual"],
  ['Mu-x']: ["Automatic","Manual"],
  ['City']: ["Automatic","Manual"],
  ['City Hatchback']: ["Automatic","Manual"],
  ['BR-V']: ["Automatic","Manual"],
  ['WR-V']: ["Automatic","Manual"],
  ['Civic']: ["Automatic","Manual"],
  ['Accord e:HEV']: ["Automatic","Manual"],
  ['HR-V e:HEV']: ["Automatic","Manual"],
  ['CR-V']: ["Automatic","Manual"],
  ['e:N1']: ["Automatic","Manual"],
  ['Everest']: ["Automatic","Manual"],
  ['Ranger']: ["Automatic","Manual"],
  ['Mirage']: ["Automatic","Manual"],
  ['Attrage']: ["Automatic","Manual"],
  ['Xpander']: ["Automatic","Manual"],
  ['Xforce']: ["Automatic","Manual"],
  ['Triton']: ["Automatic","Manual"],
  ['Pajero']: ["Automatic","Manual"],
  ['Atto 3']: ["Automatic","Manual"],
  ['Dolphin']: ["Automatic","Manual"],
  ['Seal']: ["Automatic","Manual"],
  ['Sealion 7']: ["Automatic","Manual"],
  ['M6']: ["Automatic","Manual"],
  ['Seal 5']: ["Automatic","Manual"],
  ['MG 3']: ["Automatic","Manual"],
  ['MG 5']: ["Automatic","Manual"],
  ['MG 4']: ["Automatic","Manual"],
  ['MG ZS']: ["Automatic","Manual"],
  ['MG HS']: ["Automatic","Manual"],
  ['MG EP']: ["Automatic","Manual"],
  ['MG ES']: ["Automatic","Manual"],
  ['MG VS']: ["Automatic","Manual"],
  ['MG Maxus 7']: ["Automatic","Manual"],
  ['MG Maxus 9']: ["Automatic","Manual"],
  ['MG IM6']: ["Automatic","Manual"],
  ['MG S5']: ["Automatic","Manual"],
  ['MG Cyberster']: ["Automatic","Manual"],
  ['MG Extender']: ["Automatic","Manual"],
  ['Mazda 2 Sedan']: ["Automatic","Manual"],
  ['Mazda 2 Hatchback']: ["Automatic","Manual"],
  ['Mazda 3 Sedan']: ["Automatic","Manual"],
  ['Mazda 3 Fastback']: ["Automatic","Manual"],
  ['Mazda MX-5']: ["Automatic","Manual"],
  ['Mazda CX-3']: ["Automatic","Manual"],
  ['Mazda CX-30']: ["Automatic","Manual"],
  ['Mazda CX-5']: ["Automatic","Manual"],
  ['Mazda CX-8']: ["Automatic","Manual"],
  ['Mazda BT-50']: ["Automatic","Manual"],
  ['Almera']: ["Automatic","Manual"],
  ['Sylphy']: ["Automatic","Manual"],
  ['Note']: ["Automatic","Manual"],
  ['Kicks']: ["Automatic","Manual"],
  ['X-Trail']: ["Automatic","Manual"],
  ['Terra']: ["Automatic","Manual"],
  ['Navara']: ["Automatic","Manual"],
  ['Serena']: ["Automatic","Manual"],
  ['GT-R']: ["Automatic","Manual"],
  ['Leaf']: ["Automatic","Manual"],
  ['Neta V']: ["Automatic","Manual"],
  ['Neta V-II']: ["Automatic","Manual"],
  ['Neta X']: ["Automatic","Manual"],
  ['Haval H6']: ["Automatic","Manual"],
  ['Good Cat']: ["Automatic","Manual"],
  ['07']: ["Automatic","Manual"],
  ['Tank 300']: ["Automatic","Manual"],
  ['Tank 500']: ["Automatic","Manual"],
  ['Aion Y Plus']: ["Automatic","Manual"],
  ['Aion V']: ["Automatic","Manual"],
  ['Aion UT']: ["Automatic","Manual"],
  ['M8']: ["Automatic","Manual"],
  ['L07']: ["Automatic","Manual"],
  ['S07']: ["Automatic","Manual"],
  ['S05']: ["Automatic","Manual"],
  ['G6']: ["Automatic","Manual"],
  ['X9']: ["Automatic","Manual"],
  ['X']: ["Automatic","Manual"],
  ['009']: ["Automatic","Manual"],
  ['6']: ["Automatic","Manual"],
  ['Santa Fe']: ["Automatic","Manual"],
  ['Stargazer']: ["Automatic","Manual"],
  ['Staria']: ["Automatic","Manual"],
  ['H-1']: ["Automatic","Manual"],
  ['EV5']: ["Automatic","Manual"],
  ['EV9']: ["Automatic","Manual"],
  ['Carnival']: ["Automatic","Manual"],
  ['3 Series']: ["Automatic","Manual"],
  ['5 Series']: ["Automatic","Manual"],
  ['7 Series Sedan']: ["Automatic","Manual"],
  ['i5']: ["Automatic","Manual"],
  ['i7']: ["Automatic","Manual"],
  ['X1']: ["Automatic","Manual"],
  ['X3']: ["Automatic","Manual"],
  ['Z4 Roadster']: ["Automatic","Manual"],
  ['C-Class Saloon']: ["Automatic","Manual"],
  ['E-Class Saloon']: ["Automatic","Manual"],
  ['GLC SUV']: ["Automatic","Manual"],
  ['GLA SUV']: ["Automatic","Manual"],
  ['S-Class Saloon']: ["Automatic","Manual"],
};

export default Object.freeze(CarTransmissionsByModel);
